services:
  mongo:
    image: mongo:latest
    container_name: mongo-for-ecommerce
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: farhan
      MONGO_INITDB_ROOT_PASSWORD: p3rs0nal
    command: mongod --bind_ip_all 

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-for-ecommerce
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: farhan
      ME_CONFIG_MONGODB_ADMINPASSWORD: p3rs0nal
      ME_CONFIG_MONGODB_SERVER: mongo
